apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/dev/*
build:
  local:
    push: false
  artifacts:
    - image: olstoppa/fa-be
      context: fa-be
      docker:
        dockerfile: Dockerfile
    - image: olstoppa/fa-fe
      context: fa-fe
      docker:
        dockerfile: Dockerfile
      