import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  const handleSubmit = (e: React.SyntheticEvent) => {
    e.preventDefault();
    
    const target = e.target as typeof e.target & {
      username: { value: string };
      password: { value: string };
    };

    const { username, password } = target;
    fetch('/api/login', {
      method: 'POST',
      body: JSON.stringify({
        username: username.value,
        password: password.value,
      }),
      headers: {
        'Content-Type': 'application/json'
      },
    }).then(res => {
      router.push('/');
    }).catch(e => {
      console.log(e);
    })
  }
  return (
    <>
      <Head>
        <title>Fraud Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} onSubmit={handleSubmit}>
        <div className={styles.login}>
          <form className={styles.form}>
            <input className={styles.inputField} type='text' name='username' placeholder='Username' />
            <input className={styles.inputField} type='password' name='password' placeholder='Password'/>
            <input className={styles.submitButton} type='submit' value='Login' />
          </form>
        </div>
      </main>
    </>
  )
}
